from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from worldcup_2026_bracket_guard import evaluate_bracket_readiness
from worldcup_2026_bracket_structure import BRACKET_SLOTS_PATH, write_default_bracket_files


LAYER_ROOT = Path(__file__).resolve().parent
DATA_ROOT = LAYER_ROOT / "data"
BRACKET_PROJECTION_REPORT_PATH = DATA_ROOT / "worldcup_2026_bracket_projection_report.json"


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json_if_changed(path: Path, data: dict) -> None:
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    if path.exists():
        existing = json.loads(path.read_text(encoding="utf-8"))
        comparable_existing = dict(existing)
        comparable_data = dict(data)
        comparable_existing.pop("generated_at", None)
        comparable_data.pop("generated_at", None)
        if comparable_existing == comparable_data:
            return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build_knockout_bracket(
    group_standings: dict | None = None,
    third_place_matrix: dict | None = None,
    dry_run=True,
) -> dict:
    write_default_bracket_files()
    guard = evaluate_bracket_readiness(group_standings_path=group_standings)
    slots = _load_json(BRACKET_SLOTS_PATH)
    if group_standings is None:
        result = {
            "data_status": "worldcup_2026_bracket_projection_v1",
            "generated_at": _now(),
            "builder_status": "blocked_pending_group_results",
            "dry_run": dry_run,
            "guard": guard,
            "bracket": slots,
            "warnings": [
                "No group standings were supplied; returning scaffold only.",
                "No knockout picks are generated by this builder.",
            ],
        }
        _write_json_if_changed(BRACKET_PROJECTION_REPORT_PATH, result)
        return result
    if guard["bracket_guard_status"] != "ready_for_bracket_build":
        result = {
            "data_status": "worldcup_2026_bracket_projection_v1",
            "generated_at": _now(),
            "builder_status": guard["bracket_guard_status"],
            "dry_run": dry_run,
            "guard": guard,
            "bracket": slots,
            "warnings": [
                "Bracket guard is not ready; real bracket construction is blocked.",
                "No qualified teams or third-place mappings are invented.",
            ],
        }
        _write_json_if_changed(BRACKET_PROJECTION_REPORT_PATH, result)
        return result
    if third_place_matrix is None:
        result = {
            "data_status": "worldcup_2026_bracket_projection_v1",
            "generated_at": _now(),
            "builder_status": "blocked_third_place_rules",
            "dry_run": dry_run,
            "guard": guard,
            "bracket": slots,
            "warnings": ["Third-place combination matrix is required before bracket assignment."],
        }
        _write_json_if_changed(BRACKET_PROJECTION_REPORT_PATH, result)
        return result
    result = {
        "data_status": "worldcup_2026_bracket_projection_v1",
        "generated_at": _now(),
        "builder_status": "dry_run_ready_no_active_write" if dry_run else "ready",
        "dry_run": dry_run,
        "guard": guard,
        "bracket": slots,
        "warnings": ["Operational assignment remains disabled until official mappings are verified."],
    }
    if dry_run:
        _write_json_if_changed(BRACKET_PROJECTION_REPORT_PATH, result)
    return result
